/*

 BG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\pixead\Documents\Code\GB\project-Game_Boi-\experiments\C\character_scroll\bg_sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg_mapWidth 32
#define bg_mapHeight 32
#define bg_mapBank 0

extern unsigned char bg_map[];

/* End of BG_MAP.H */
