/*

 BG_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bg_spritesBank 0

/* Super Gameboy palette 0 */
#define bg_spritesSGBPal0c0 6076
#define bg_spritesSGBPal0c1 8935
#define bg_spritesSGBPal0c2 6596
#define bg_spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bg_spritesSGBPal1c0 6076
#define bg_spritesSGBPal1c1 8935
#define bg_spritesSGBPal1c2 6596
#define bg_spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bg_spritesSGBPal2c0 6076
#define bg_spritesSGBPal2c1 8935
#define bg_spritesSGBPal2c2 6596
#define bg_spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bg_spritesSGBPal3c0 6076
#define bg_spritesSGBPal3c1 8935
#define bg_spritesSGBPal3c2 6596
#define bg_spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bg_spritesCGBPal0c0 32767
#define BG_GREY 10570
#define BG_RED 30
#define BG_GREEN 5344

/* Gameboy Color palette 1 */
#define bg_spritesCGBPal1c0 32767
#define bg_spritesCGBPal1c1 21140
#define bg_spritesCGBPal1c2 30
#define bg_spritesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define bg_spritesCGBPal2c0 6076
#define bg_spritesCGBPal2c1 8935
#define bg_spritesCGBPal2c2 6596
#define bg_spritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define bg_spritesCGBPal3c0 6076
#define bg_spritesCGBPal3c1 8935
#define bg_spritesCGBPal3c2 6596
#define bg_spritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define bg_spritesCGBPal4c0 6076
#define bg_spritesCGBPal4c1 8935
#define bg_spritesCGBPal4c2 6596
#define bg_spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bg_spritesCGBPal5c0 6076
#define bg_spritesCGBPal5c1 8935
#define bg_spritesCGBPal5c2 6596
#define bg_spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bg_spritesCGBPal6c0 6076
#define bg_spritesCGBPal6c1 8935
#define bg_spritesCGBPal6c2 6596
#define bg_spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bg_spritesCGBPal7c0 6076
#define bg_spritesCGBPal7c1 8935
#define bg_spritesCGBPal7c2 6596
#define bg_spritesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bg_spritesCGB[];
/* Start of tile array. */
extern unsigned char bg_sprites[];

/* End of BG_SPRITES.H */
