/*

 BG_SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char bg_spritesCGB[] =
{
  0x00,0x00
};
/* Start of tile array. */
unsigned char bg_sprites[] =
{
  0x00,0x55,0x00,0xAA,0x00,0x55,0x00,0xAA,
  0x00,0x55,0x00,0xAA,0x00,0x55,0x00,0xAA,
  0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,
  0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00
};

/* End of BG_SPRITES.C */
